# A simple Makefile generated by Simple-Console
CC = g++
FILES = main.cpp src/server/server.cpp src/token/token.cpp include/crow/crow_all.h include/httplib/httplib.h include/jwt-cpp/base.h include/jwt-cpp/jwt.h include/nlohmann/json.hpp include/picojson/picojson.h
DEPS = -w -lfmt -lboost_system -lpthread -lssl -lcrypto
OUTPUT = build/main
all : ${FILES}
# make only uses tabs and not spaces for indents
	${CC} ${FILES} -o ${OUTPUT} ${DEPS}